/* tslint:disable */
/* eslint-disable */
/**
 * analytics.athoscommerce.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.52
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
	ChatAddtocartSchema,
	ChatClickthroughSchema,
	ChatFeedbackSchema,
	ChatImpressionSchema,
	ErrorResponseBody,
	InlineObject,
	InlineObject1,
} from '../models/index';
import {
	ChatAddtocartSchemaFromJSON,
	ChatAddtocartSchemaToJSON,
	ChatClickthroughSchemaFromJSON,
	ChatClickthroughSchemaToJSON,
	ChatFeedbackSchemaFromJSON,
	ChatFeedbackSchemaToJSON,
	ChatImpressionSchemaFromJSON,
	ChatImpressionSchemaToJSON,
	ErrorResponseBodyFromJSON,
	ErrorResponseBodyToJSON,
	InlineObjectFromJSON,
	InlineObjectToJSON,
	InlineObject1FromJSON,
	InlineObject1ToJSON,
} from '../models/index';

export interface ChatAddtocartRequest {
	siteId: string;
	chatAddtocartSchema: ChatAddtocartSchema;
}

export interface ChatClickthroughRequest {
	siteId: string;
	chatClickthroughSchema: ChatClickthroughSchema;
}

export interface ChatFeedbackRequest {
	siteId: string;
	chatFeedbackSchema: ChatFeedbackSchema;
}

export interface ChatImpressionRequest {
	siteId: string;
	chatImpressionSchema: ChatImpressionSchema;
}

/**
 *
 */
export class ChatApi extends runtime.BaseAPI {
	/**
	 * <i>/beacon/v2/{siteId}/chat/addtocart</i><br><br>This event should be triggered when a shopper interacts with Chat where Athos Commerce results are rendered, and adds a result to the cart via a `Quick Add to Cart` button.
	 * addtocart
	 */
	async chatAddtocartRaw(
		requestParameters: ChatAddtocartRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<InlineObject>> {
		if (requestParameters['siteId'] == null) {
			throw new runtime.RequiredError('siteId', 'Required parameter "siteId" was null or undefined when calling chatAddtocart().');
		}

		if (requestParameters['chatAddtocartSchema'] == null) {
			throw new runtime.RequiredError(
				'chatAddtocartSchema',
				'Required parameter "chatAddtocartSchema" was null or undefined when calling chatAddtocart().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters['Content-Type'] = 'text/plain';

		let urlPath = `/{siteId}/chat/addtocart`;
		urlPath = urlPath.replace(`{${'siteId'}}`, encodeURIComponent(String(requestParameters['siteId'])));

		const response = await this.request(
			{
				path: urlPath,
				method: 'POST',
				headers: headerParameters,
				query: queryParameters,
				body: ChatAddtocartSchemaToJSON(requestParameters['chatAddtocartSchema']),
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) => InlineObjectFromJSON(jsonValue));
	}

	/**
	 * <i>/beacon/v2/{siteId}/chat/addtocart</i><br><br>This event should be triggered when a shopper interacts with Chat where Athos Commerce results are rendered, and adds a result to the cart via a `Quick Add to Cart` button.
	 * addtocart
	 */
	async chatAddtocart(requestParameters: ChatAddtocartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InlineObject> {
		const response = await this.chatAddtocartRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * <i>/beacon/v2/{siteId}/chat/clickthrough</i><br><br>This event should be triggered when a shopper interacts with Chat, clicks on a Athos Commerce result, and will be taken to the product detail page (PDP).
	 * clickthrough
	 */
	async chatClickthroughRaw(
		requestParameters: ChatClickthroughRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<InlineObject>> {
		if (requestParameters['siteId'] == null) {
			throw new runtime.RequiredError('siteId', 'Required parameter "siteId" was null or undefined when calling chatClickthrough().');
		}

		if (requestParameters['chatClickthroughSchema'] == null) {
			throw new runtime.RequiredError(
				'chatClickthroughSchema',
				'Required parameter "chatClickthroughSchema" was null or undefined when calling chatClickthrough().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters['Content-Type'] = 'text/plain';

		let urlPath = `/{siteId}/chat/clickthrough`;
		urlPath = urlPath.replace(`{${'siteId'}}`, encodeURIComponent(String(requestParameters['siteId'])));

		const response = await this.request(
			{
				path: urlPath,
				method: 'POST',
				headers: headerParameters,
				query: queryParameters,
				body: ChatClickthroughSchemaToJSON(requestParameters['chatClickthroughSchema']),
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) => InlineObjectFromJSON(jsonValue));
	}

	/**
	 * <i>/beacon/v2/{siteId}/chat/clickthrough</i><br><br>This event should be triggered when a shopper interacts with Chat, clicks on a Athos Commerce result, and will be taken to the product detail page (PDP).
	 * clickthrough
	 */
	async chatClickthrough(
		requestParameters: ChatClickthroughRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<InlineObject> {
		const response = await this.chatClickthroughRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * <i>/beacon/v2/{siteId}/chat/feedback</i><br><br>This event should be triggered when a shopper provides feedback to Chat.
	 * feedback
	 */
	async chatFeedbackRaw(
		requestParameters: ChatFeedbackRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<InlineObject>> {
		if (requestParameters['siteId'] == null) {
			throw new runtime.RequiredError('siteId', 'Required parameter "siteId" was null or undefined when calling chatFeedback().');
		}

		if (requestParameters['chatFeedbackSchema'] == null) {
			throw new runtime.RequiredError(
				'chatFeedbackSchema',
				'Required parameter "chatFeedbackSchema" was null or undefined when calling chatFeedback().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters['Content-Type'] = 'text/plain';

		let urlPath = `/{siteId}/chat/feedback`;
		urlPath = urlPath.replace(`{${'siteId'}}`, encodeURIComponent(String(requestParameters['siteId'])));

		const response = await this.request(
			{
				path: urlPath,
				method: 'POST',
				headers: headerParameters,
				query: queryParameters,
				body: ChatFeedbackSchemaToJSON(requestParameters['chatFeedbackSchema']),
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) => InlineObjectFromJSON(jsonValue));
	}

	/**
	 * <i>/beacon/v2/{siteId}/chat/feedback</i><br><br>This event should be triggered when a shopper provides feedback to Chat.
	 * feedback
	 */
	async chatFeedback(requestParameters: ChatFeedbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InlineObject> {
		const response = await this.chatFeedbackRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * <i>/beacon/v2/{siteId}/chat/impression</i><br><br>This event should be triggered when a shopper interacts with Chat and Athos Commerce results receive an impression.
	 * impression
	 */
	async chatImpressionRaw(
		requestParameters: ChatImpressionRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<InlineObject>> {
		if (requestParameters['siteId'] == null) {
			throw new runtime.RequiredError('siteId', 'Required parameter "siteId" was null or undefined when calling chatImpression().');
		}

		if (requestParameters['chatImpressionSchema'] == null) {
			throw new runtime.RequiredError(
				'chatImpressionSchema',
				'Required parameter "chatImpressionSchema" was null or undefined when calling chatImpression().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters['Content-Type'] = 'text/plain';

		let urlPath = `/{siteId}/chat/impression`;
		urlPath = urlPath.replace(`{${'siteId'}}`, encodeURIComponent(String(requestParameters['siteId'])));

		const response = await this.request(
			{
				path: urlPath,
				method: 'POST',
				headers: headerParameters,
				query: queryParameters,
				body: ChatImpressionSchemaToJSON(requestParameters['chatImpressionSchema']),
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) => InlineObjectFromJSON(jsonValue));
	}

	/**
	 * <i>/beacon/v2/{siteId}/chat/impression</i><br><br>This event should be triggered when a shopper interacts with Chat and Athos Commerce results receive an impression.
	 * impression
	 */
	async chatImpression(requestParameters: ChatImpressionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InlineObject> {
		const response = await this.chatImpressionRaw(requestParameters, initOverrides);
		return await response.value();
	}
}
