/* tslint:disable */
/* eslint-disable */
/**
 * analytics.athoscommerce.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.52
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatResultProductType } from './ChatResultProductType';
import {
	ChatResultProductTypeFromJSON,
	ChatResultProductTypeFromJSONTyped,
	ChatResultProductTypeToJSON,
	ChatResultProductTypeToJSONTyped,
} from './ChatResultProductType';

/**
 * Describes a tracked result.
 * @export
 * @interface ChatResultProduct
 */
export interface ChatResultProduct {
	/**
	 *
	 * @type {ChatResultProductType}
	 * @memberof ChatResultProduct
	 */
	type: ChatResultProductType;
	/**
	 * Unique product identifier of the parent product interacted with
	 * @type {string}
	 * @memberof ChatResultProduct
	 */
	parentId: string;
	/**
	 * Unique product identifier of the product interacted with
	 * @type {string}
	 * @memberof ChatResultProduct
	 */
	uid: string;
	/**
	 * SKU of the product interacted with
	 * @type {string}
	 * @memberof ChatResultProduct
	 */
	sku?: string;
}

/**
 * Check if a given object implements the ChatResultProduct interface.
 */
export function instanceOfChatResultProduct(value: object): value is ChatResultProduct {
	if (!('type' in value) || value['type'] === undefined) return false;
	if (!('parentId' in value) || value['parentId'] === undefined) return false;
	if (!('uid' in value) || value['uid'] === undefined) return false;
	return true;
}

export function ChatResultProductFromJSON(json: any): ChatResultProduct {
	return ChatResultProductFromJSONTyped(json, false);
}

export function ChatResultProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatResultProduct {
	if (json == null) {
		return json;
	}
	return {
		type: ChatResultProductTypeFromJSON(json['type']),
		parentId: json['parentId'],
		uid: json['uid'],
		sku: json['sku'] == null ? undefined : json['sku'],
	};
}

export function ChatResultProductToJSON(json: any): ChatResultProduct {
	return ChatResultProductToJSONTyped(json, false);
}

export function ChatResultProductToJSONTyped(value?: ChatResultProduct | null, ignoreDiscriminator: boolean = false): any {
	if (value == null) {
		return value;
	}

	return {
		type: ChatResultProductTypeToJSON(value['type']),
		parentId: value['parentId'],
		uid: value['uid'],
		sku: value['sku'],
	};
}
