/* tslint:disable */
/* eslint-disable */
/**
 * analytics.athoscommerce.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.52
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatResultProduct } from './ChatResultProduct';
import {
	ChatResultProductFromJSON,
	ChatResultProductFromJSONTyped,
	ChatResultProductToJSON,
	ChatResultProductToJSONTyped,
} from './ChatResultProduct';

/**
 * Event details
 * @export
 * @interface ChatClickthroughSchemaData
 */
export interface ChatClickthroughSchemaData {
	/**
	 * Unique ID for the chat session, used to associate events with a specific conversation. Should be generated at the start of a chat session and remain consistent across all events within that session.
	 * @type {string}
	 * @memberof ChatClickthroughSchemaData
	 */
	chatSessionId: string;
	/**
	 * Unique ID returned in each API response
	 * @type {string}
	 * @memberof ChatClickthroughSchemaData
	 */
	responseId: string;
	/**
	 * List of tracked result(s).
	 * @type {Array<ChatResultProduct>}
	 * @memberof ChatClickthroughSchemaData
	 */
	results: Array<ChatResultProduct>;
}

/**
 * Check if a given object implements the ChatClickthroughSchemaData interface.
 */
export function instanceOfChatClickthroughSchemaData(value: object): value is ChatClickthroughSchemaData {
	if (!('chatSessionId' in value) || value['chatSessionId'] === undefined) return false;
	if (!('responseId' in value) || value['responseId'] === undefined) return false;
	if (!('results' in value) || value['results'] === undefined) return false;
	return true;
}

export function ChatClickthroughSchemaDataFromJSON(json: any): ChatClickthroughSchemaData {
	return ChatClickthroughSchemaDataFromJSONTyped(json, false);
}

export function ChatClickthroughSchemaDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatClickthroughSchemaData {
	if (json == null) {
		return json;
	}
	return {
		chatSessionId: json['chatSessionId'],
		responseId: json['responseId'],
		results: (json['results'] as Array<any>).map(ChatResultProductFromJSON),
	};
}

export function ChatClickthroughSchemaDataToJSON(json: any): ChatClickthroughSchemaData {
	return ChatClickthroughSchemaDataToJSONTyped(json, false);
}

export function ChatClickthroughSchemaDataToJSONTyped(value?: ChatClickthroughSchemaData | null, ignoreDiscriminator: boolean = false): any {
	if (value == null) {
		return value;
	}

	return {
		chatSessionId: value['chatSessionId'],
		responseId: value['responseId'],
		results: (value['results'] as Array<any>).map(ChatResultProductToJSON),
	};
}
