/* tslint:disable */
/* eslint-disable */
/**
 * analytics.athoscommerce.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.52
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatFeedbackSchemaData } from './ChatFeedbackSchemaData';
import {
	ChatFeedbackSchemaDataFromJSON,
	ChatFeedbackSchemaDataFromJSONTyped,
	ChatFeedbackSchemaDataToJSON,
	ChatFeedbackSchemaDataToJSONTyped,
} from './ChatFeedbackSchemaData';
import type { Context } from './Context';
import { ContextFromJSON, ContextFromJSONTyped, ContextToJSON, ContextToJSONTyped } from './Context';

/**
 *
 * @export
 * @interface ChatFeedbackSchema
 */
export interface ChatFeedbackSchema {
	/**
	 *
	 * @type {Context}
	 * @memberof ChatFeedbackSchema
	 */
	context: Context;
	/**
	 *
	 * @type {ChatFeedbackSchemaData}
	 * @memberof ChatFeedbackSchema
	 */
	data: ChatFeedbackSchemaData;
}

/**
 * Check if a given object implements the ChatFeedbackSchema interface.
 */
export function instanceOfChatFeedbackSchema(value: object): value is ChatFeedbackSchema {
	if (!('context' in value) || value['context'] === undefined) return false;
	if (!('data' in value) || value['data'] === undefined) return false;
	return true;
}

export function ChatFeedbackSchemaFromJSON(json: any): ChatFeedbackSchema {
	return ChatFeedbackSchemaFromJSONTyped(json, false);
}

export function ChatFeedbackSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatFeedbackSchema {
	if (json == null) {
		return json;
	}
	return {
		context: ContextFromJSON(json['context']),
		data: ChatFeedbackSchemaDataFromJSON(json['data']),
	};
}

export function ChatFeedbackSchemaToJSON(json: any): ChatFeedbackSchema {
	return ChatFeedbackSchemaToJSONTyped(json, false);
}

export function ChatFeedbackSchemaToJSONTyped(value?: ChatFeedbackSchema | null, ignoreDiscriminator: boolean = false): any {
	if (value == null) {
		return value;
	}

	return {
		context: ContextToJSON(value['context']),
		data: ChatFeedbackSchemaDataToJSON(value['data']),
	};
}
