/* tslint:disable */
/* eslint-disable */
/**
 * analytics.athoscommerce.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.52
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Product } from './Product';
import { ProductFromJSON, ProductFromJSONTyped, ProductToJSON, ProductToJSONTyped } from './Product';

/**
 * Event details
 * @export
 * @interface ChatAddtocartSchemaData
 */
export interface ChatAddtocartSchemaData {
	/**
	 * Unique ID for the chat session, used to associate events with a specific conversation. Should be generated at the start of a chat session and remain consistent across all events within that session.
	 * @type {string}
	 * @memberof ChatAddtocartSchemaData
	 */
	chatSessionId: string;
	/**
	 * Unique ID returned in each API response
	 * @type {string}
	 * @memberof ChatAddtocartSchemaData
	 */
	responseId: string;
	/**
	 * Products added to the cart
	 * @type {Array<Product>}
	 * @memberof ChatAddtocartSchemaData
	 */
	results: Array<Product>;
}

/**
 * Check if a given object implements the ChatAddtocartSchemaData interface.
 */
export function instanceOfChatAddtocartSchemaData(value: object): value is ChatAddtocartSchemaData {
	if (!('chatSessionId' in value) || value['chatSessionId'] === undefined) return false;
	if (!('responseId' in value) || value['responseId'] === undefined) return false;
	if (!('results' in value) || value['results'] === undefined) return false;
	return true;
}

export function ChatAddtocartSchemaDataFromJSON(json: any): ChatAddtocartSchemaData {
	return ChatAddtocartSchemaDataFromJSONTyped(json, false);
}

export function ChatAddtocartSchemaDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatAddtocartSchemaData {
	if (json == null) {
		return json;
	}
	return {
		chatSessionId: json['chatSessionId'],
		responseId: json['responseId'],
		results: (json['results'] as Array<any>).map(ProductFromJSON),
	};
}

export function ChatAddtocartSchemaDataToJSON(json: any): ChatAddtocartSchemaData {
	return ChatAddtocartSchemaDataToJSONTyped(json, false);
}

export function ChatAddtocartSchemaDataToJSONTyped(value?: ChatAddtocartSchemaData | null, ignoreDiscriminator: boolean = false): any {
	if (value == null) {
		return value;
	}

	return {
		chatSessionId: value['chatSessionId'],
		responseId: value['responseId'],
		results: (value['results'] as Array<any>).map(ProductToJSON),
	};
}
