/* tslint:disable */
/* eslint-disable */
/**
 * analytics.athoscommerce.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.52
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Context } from './Context';
import { ContextFromJSON, ContextFromJSONTyped, ContextToJSON, ContextToJSONTyped } from './Context';
import type { ChatClickthroughSchemaData } from './ChatClickthroughSchemaData';
import {
	ChatClickthroughSchemaDataFromJSON,
	ChatClickthroughSchemaDataFromJSONTyped,
	ChatClickthroughSchemaDataToJSON,
	ChatClickthroughSchemaDataToJSONTyped,
} from './ChatClickthroughSchemaData';

/**
 *
 * @export
 * @interface ChatClickthroughSchema
 */
export interface ChatClickthroughSchema {
	/**
	 *
	 * @type {Context}
	 * @memberof ChatClickthroughSchema
	 */
	context: Context;
	/**
	 *
	 * @type {ChatClickthroughSchemaData}
	 * @memberof ChatClickthroughSchema
	 */
	data: ChatClickthroughSchemaData;
}

/**
 * Check if a given object implements the ChatClickthroughSchema interface.
 */
export function instanceOfChatClickthroughSchema(value: object): value is ChatClickthroughSchema {
	if (!('context' in value) || value['context'] === undefined) return false;
	if (!('data' in value) || value['data'] === undefined) return false;
	return true;
}

export function ChatClickthroughSchemaFromJSON(json: any): ChatClickthroughSchema {
	return ChatClickthroughSchemaFromJSONTyped(json, false);
}

export function ChatClickthroughSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatClickthroughSchema {
	if (json == null) {
		return json;
	}
	return {
		context: ContextFromJSON(json['context']),
		data: ChatClickthroughSchemaDataFromJSON(json['data']),
	};
}

export function ChatClickthroughSchemaToJSON(json: any): ChatClickthroughSchema {
	return ChatClickthroughSchemaToJSONTyped(json, false);
}

export function ChatClickthroughSchemaToJSONTyped(value?: ChatClickthroughSchema | null, ignoreDiscriminator: boolean = false): any {
	if (value == null) {
		return value;
	}

	return {
		context: ContextToJSON(value['context']),
		data: ChatClickthroughSchemaDataToJSON(value['data']),
	};
}
