/* tslint:disable */
/* eslint-disable */
/**
 * analytics.athoscommerce.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.52
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Event details
 * @export
 * @interface ChatFeedbackSchemaData
 */
export interface ChatFeedbackSchemaData {
	/**
	 * Unique ID for the chat session, used to associate events with a specific conversation. Should be generated at the start of a chat session and remain consistent across all events within that session.
	 * @type {string}
	 * @memberof ChatFeedbackSchemaData
	 */
	chatSessionId: string;
	/**
	 * Indicates whether the feedback is positive (true) or negative (false)
	 * @type {boolean}
	 * @memberof ChatFeedbackSchemaData
	 */
	feedback: boolean;
}

/**
 * Check if a given object implements the ChatFeedbackSchemaData interface.
 */
export function instanceOfChatFeedbackSchemaData(value: object): value is ChatFeedbackSchemaData {
	if (!('chatSessionId' in value) || value['chatSessionId'] === undefined) return false;
	if (!('feedback' in value) || value['feedback'] === undefined) return false;
	return true;
}

export function ChatFeedbackSchemaDataFromJSON(json: any): ChatFeedbackSchemaData {
	return ChatFeedbackSchemaDataFromJSONTyped(json, false);
}

export function ChatFeedbackSchemaDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatFeedbackSchemaData {
	if (json == null) {
		return json;
	}
	return {
		chatSessionId: json['chatSessionId'],
		feedback: json['feedback'],
	};
}

export function ChatFeedbackSchemaDataToJSON(json: any): ChatFeedbackSchemaData {
	return ChatFeedbackSchemaDataToJSONTyped(json, false);
}

export function ChatFeedbackSchemaDataToJSONTyped(value?: ChatFeedbackSchemaData | null, ignoreDiscriminator: boolean = false): any {
	if (value == null) {
		return value;
	}

	return {
		chatSessionId: value['chatSessionId'],
		feedback: value['feedback'],
	};
}
