/* tslint:disable */
/* eslint-disable */
/**
 * analytics.athoscommerce.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.52
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Context } from './Context';
import { ContextFromJSON, ContextFromJSONTyped, ContextToJSON, ContextToJSONTyped } from './Context';
import type { ChatAddtocartSchemaData } from './ChatAddtocartSchemaData';
import {
	ChatAddtocartSchemaDataFromJSON,
	ChatAddtocartSchemaDataFromJSONTyped,
	ChatAddtocartSchemaDataToJSON,
	ChatAddtocartSchemaDataToJSONTyped,
} from './ChatAddtocartSchemaData';

/**
 *
 * @export
 * @interface ChatAddtocartSchema
 */
export interface ChatAddtocartSchema {
	/**
	 *
	 * @type {Context}
	 * @memberof ChatAddtocartSchema
	 */
	context: Context;
	/**
	 *
	 * @type {ChatAddtocartSchemaData}
	 * @memberof ChatAddtocartSchema
	 */
	data: ChatAddtocartSchemaData;
}

/**
 * Check if a given object implements the ChatAddtocartSchema interface.
 */
export function instanceOfChatAddtocartSchema(value: object): value is ChatAddtocartSchema {
	if (!('context' in value) || value['context'] === undefined) return false;
	if (!('data' in value) || value['data'] === undefined) return false;
	return true;
}

export function ChatAddtocartSchemaFromJSON(json: any): ChatAddtocartSchema {
	return ChatAddtocartSchemaFromJSONTyped(json, false);
}

export function ChatAddtocartSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatAddtocartSchema {
	if (json == null) {
		return json;
	}
	return {
		context: ContextFromJSON(json['context']),
		data: ChatAddtocartSchemaDataFromJSON(json['data']),
	};
}

export function ChatAddtocartSchemaToJSON(json: any): ChatAddtocartSchema {
	return ChatAddtocartSchemaToJSONTyped(json, false);
}

export function ChatAddtocartSchemaToJSONTyped(value?: ChatAddtocartSchema | null, ignoreDiscriminator: boolean = false): any {
	if (value == null) {
		return value;
	}

	return {
		context: ContextToJSON(value['context']),
		data: ChatAddtocartSchemaDataToJSON(value['data']),
	};
}
