/* tslint:disable */
/* eslint-disable */
/**
 * analytics.athoscommerce.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.52
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Context } from './Context';
import { ContextFromJSON, ContextFromJSONTyped, ContextToJSON, ContextToJSONTyped } from './Context';
import type { ChatImpressionSchemaData } from './ChatImpressionSchemaData';
import {
	ChatImpressionSchemaDataFromJSON,
	ChatImpressionSchemaDataFromJSONTyped,
	ChatImpressionSchemaDataToJSON,
	ChatImpressionSchemaDataToJSONTyped,
} from './ChatImpressionSchemaData';

/**
 *
 * @export
 * @interface ChatImpressionSchema
 */
export interface ChatImpressionSchema {
	/**
	 *
	 * @type {Context}
	 * @memberof ChatImpressionSchema
	 */
	context: Context;
	/**
	 *
	 * @type {ChatImpressionSchemaData}
	 * @memberof ChatImpressionSchema
	 */
	data: ChatImpressionSchemaData;
}

/**
 * Check if a given object implements the ChatImpressionSchema interface.
 */
export function instanceOfChatImpressionSchema(value: object): value is ChatImpressionSchema {
	if (!('context' in value) || value['context'] === undefined) return false;
	if (!('data' in value) || value['data'] === undefined) return false;
	return true;
}

export function ChatImpressionSchemaFromJSON(json: any): ChatImpressionSchema {
	return ChatImpressionSchemaFromJSONTyped(json, false);
}

export function ChatImpressionSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatImpressionSchema {
	if (json == null) {
		return json;
	}
	return {
		context: ContextFromJSON(json['context']),
		data: ChatImpressionSchemaDataFromJSON(json['data']),
	};
}

export function ChatImpressionSchemaToJSON(json: any): ChatImpressionSchema {
	return ChatImpressionSchemaToJSONTyped(json, false);
}

export function ChatImpressionSchemaToJSONTyped(value?: ChatImpressionSchema | null, ignoreDiscriminator: boolean = false): any {
	if (value == null) {
		return value;
	}

	return {
		context: ContextToJSON(value['context']),
		data: ChatImpressionSchemaDataToJSON(value['data']),
	};
}
