/* tslint:disable */
/* eslint-disable */
/**
 * analytics.athoscommerce.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.52
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Defines the type of item tracked.
 * @export
 */
export const ChatResultProductType = {
	Product: 'product',
} as const;
export type ChatResultProductType = (typeof ChatResultProductType)[keyof typeof ChatResultProductType];

export function instanceOfChatResultProductType(value: any): boolean {
	for (const key in ChatResultProductType) {
		if (Object.prototype.hasOwnProperty.call(ChatResultProductType, key)) {
			if (ChatResultProductType[key as keyof typeof ChatResultProductType] === value) {
				return true;
			}
		}
	}
	return false;
}

export function ChatResultProductTypeFromJSON(json: any): ChatResultProductType {
	return ChatResultProductTypeFromJSONTyped(json, false);
}

export function ChatResultProductTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatResultProductType {
	return json as ChatResultProductType;
}

export function ChatResultProductTypeToJSON(value?: ChatResultProductType | null): any {
	return value as any;
}

export function ChatResultProductTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): ChatResultProductType {
	return value as ChatResultProductType;
}
