/* tslint:disable */
/* eslint-disable */
/**
 * analytics.athoscommerce.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.52
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Context } from './Context';
import { ContextFromJSON, ContextFromJSONTyped, ContextToJSON, ContextToJSONTyped } from './Context';
import type { FeedbackSchemaData } from './FeedbackSchemaData';
import {
	FeedbackSchemaDataFromJSON,
	FeedbackSchemaDataFromJSONTyped,
	FeedbackSchemaDataToJSON,
	FeedbackSchemaDataToJSONTyped,
} from './FeedbackSchemaData';

/**
 *
 * @export
 * @interface FeedbackSchema
 */
export interface FeedbackSchema {
	/**
	 *
	 * @type {Context}
	 * @memberof FeedbackSchema
	 */
	context: Context;
	/**
	 *
	 * @type {FeedbackSchemaData}
	 * @memberof FeedbackSchema
	 */
	data: FeedbackSchemaData;
}

/**
 * Check if a given object implements the FeedbackSchema interface.
 */
export function instanceOfFeedbackSchema(value: object): value is FeedbackSchema {
	if (!('context' in value) || value['context'] === undefined) return false;
	if (!('data' in value) || value['data'] === undefined) return false;
	return true;
}

export function FeedbackSchemaFromJSON(json: any): FeedbackSchema {
	return FeedbackSchemaFromJSONTyped(json, false);
}

export function FeedbackSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedbackSchema {
	if (json == null) {
		return json;
	}
	return {
		context: ContextFromJSON(json['context']),
		data: FeedbackSchemaDataFromJSON(json['data']),
	};
}

export function FeedbackSchemaToJSON(json: any): FeedbackSchema {
	return FeedbackSchemaToJSONTyped(json, false);
}

export function FeedbackSchemaToJSONTyped(value?: FeedbackSchema | null, ignoreDiscriminator: boolean = false): any {
	if (value == null) {
		return value;
	}

	return {
		context: ContextToJSON(value['context']),
		data: FeedbackSchemaDataToJSON(value['data']),
	};
}
