/* tslint:disable */
/* eslint-disable */
/**
 * beacon.searchspring.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Describes a tracked Searchspring result.
 * @export
 * @interface Item
 */
export interface Item {
    /**
     * Defines the type of item tracked.
     * @type {string}
     * @memberof Item
     */
    type: ItemTypeEnum;
    /**
     * Index of the result returned in the Searchspring results. The first result is 1, the second is 2, etc.
     * @type {number}
     * @memberof Item
     */
    position: number;
    /**
     * Unique product identifier of the Searchspring indexed product (also provide `sku`, `childSku`, and `childId` if available)
     * @type {string}
     * @memberof Item
     */
    uid: string;
    /**
     * Unique product variant identifier
     * @type {string}
     * @memberof Item
     */
    childUid?: string;
    /**
     * Unique product identifier (also provide `childSku` if available)
     * @type {string}
     * @memberof Item
     */
    sku?: string;
    /**
     * Unique product variant identifier (also provide `sku` if available)
     * @type {string}
     * @memberof Item
     */
    childSku?: string;
}


/**
 * @export
 */
export const ItemTypeEnum = {
    Product: 'product',
    Banner: 'banner'
} as const;
export type ItemTypeEnum = typeof ItemTypeEnum[keyof typeof ItemTypeEnum];


/**
 * Check if a given object implements the Item interface.
 */
export function instanceOfItem(value: object): value is Item {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('position' in value) || value['position'] === undefined) return false;
    if (!('uid' in value) || value['uid'] === undefined) return false;
    return true;
}

export function ItemFromJSON(json: any): Item {
    return ItemFromJSONTyped(json, false);
}

export function ItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): Item {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'position': json['position'],
        'uid': json['uid'],
        'childUid': json['childUid'] == null ? undefined : json['childUid'],
        'sku': json['sku'] == null ? undefined : json['sku'],
        'childSku': json['childSku'] == null ? undefined : json['childSku'],
    };
}

  export function ItemToJSON(json: any): Item {
      return ItemToJSONTyped(json, false);
  }

  export function ItemToJSONTyped(value?: Item | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'position': value['position'],
        'uid': value['uid'],
        'childUid': value['childUid'],
        'sku': value['sku'],
        'childSku': value['childSku'],
    };
}

