/* tslint:disable */
/* eslint-disable */
/**
 * analytics.athoscommerce.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.52
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SearchAddtocartProduct } from './SearchAddtocartProduct';
import {
	SearchAddtocartProductFromJSON,
	SearchAddtocartProductFromJSONTyped,
	SearchAddtocartProductToJSON,
	SearchAddtocartProductToJSONTyped,
} from './SearchAddtocartProduct';

/**
 * Event details
 * @export
 * @interface SearchAddtocartSchemaData
 */
export interface SearchAddtocartSchemaData {
	/**
	 * Unique ID returned in each API response
	 * @type {string}
	 * @memberof SearchAddtocartSchemaData
	 */
	responseId: string;
	/**
	 * Products added to the cart
	 * @type {Array<SearchAddtocartProduct>}
	 * @memberof SearchAddtocartSchemaData
	 */
	results: Array<SearchAddtocartProduct>;
	/**
	 * Indicates whether the event originated from a quick view popup or a regular page
	 * @type {boolean}
	 * @memberof SearchAddtocartSchemaData
	 */
	quickView?: boolean;
}

/**
 * Check if a given object implements the SearchAddtocartSchemaData interface.
 */
export function instanceOfSearchAddtocartSchemaData(value: object): value is SearchAddtocartSchemaData {
	if (!('responseId' in value) || value['responseId'] === undefined) return false;
	if (!('results' in value) || value['results'] === undefined) return false;
	return true;
}

export function SearchAddtocartSchemaDataFromJSON(json: any): SearchAddtocartSchemaData {
	return SearchAddtocartSchemaDataFromJSONTyped(json, false);
}

export function SearchAddtocartSchemaDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchAddtocartSchemaData {
	if (json == null) {
		return json;
	}
	return {
		responseId: json['responseId'],
		results: (json['results'] as Array<any>).map(SearchAddtocartProductFromJSON),
		quickView: json['quickView'] == null ? undefined : json['quickView'],
	};
}

export function SearchAddtocartSchemaDataToJSON(json: any): SearchAddtocartSchemaData {
	return SearchAddtocartSchemaDataToJSONTyped(json, false);
}

export function SearchAddtocartSchemaDataToJSONTyped(value?: SearchAddtocartSchemaData | null, ignoreDiscriminator: boolean = false): any {
	if (value == null) {
		return value;
	}

	return {
		responseId: value['responseId'],
		results: (value['results'] as Array<any>).map(SearchAddtocartProductToJSON),
		quickView: value['quickView'],
	};
}
